# Generated by Django 4.1.7 on 2023-03-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yizhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NA_zh', models.TextField(verbose_name='Answer_zh')),
                ('NQ_zh', models.TextField(verbose_name='Question_zh')),
                ('NA_en', models.TextField(verbose_name='Answer_en')),
                ('NQ_en', models.TextField(verbose_name='Question_en')),
                ('NA_ru', models.TextField(verbose_name='Answer_ru')),
                ('NQ_ru', models.TextField(verbose_name='Question_ru')),
            ],
        ),
    ]
