# Generated by Django 4.1.7 on 2023-03-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yizhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('firstname', models.CharField(default='', max_length=50, null=True, verbose_name='名')),
                ('lasttname', models.CharField(default='', max_length=50, null=True, verbose_name='姓')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机号')),
                ('addr1', models.CharField(max_length=50, null=True, verbose_name='地址')),
                ('addr2', models.CharField(max_length=50, null=True, verbose_name='备用地址')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='城市')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='国家')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='州')),
                ('zip', models.CharField(max_length=20, null=True, verbose_name='邮编')),
            ],
        ),
    ]
