# Generated by Django 4.1.7 on 2023-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yizhan', '0003_alter_user_options_alter_yizhan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yizhan',
            name='NA_en',
            field=models.TextField(null=True, verbose_name='Answer_en'),
        ),
        migrations.AlterField(
            model_name='yizhan',
            name='NA_ru',
            field=models.TextField(null=True, verbose_name='Answer_ru'),
        ),
        migrations.AlterField(
            model_name='yizhan',
            name='NA_zh',
            field=models.TextField(null=True, verbose_name='Answer_zh'),
        ),
        migrations.AlterField(
            model_name='yizhan',
            name='NQ_en',
            field=models.TextField(null=True, verbose_name='Question_en'),
        ),
        migrations.AlterField(
            model_name='yizhan',
            name='NQ_ru',
            field=models.TextField(null=True, verbose_name='Question_ru'),
        ),
        migrations.AlterField(
            model_name='yizhan',
            name='NQ_zh',
            field=models.TextField(null=True, verbose_name='Question_zh'),
        ),
    ]
